# Generated by Django 4.1.5 on 2023-01-09 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(default='admin', max_length=100)),
                ('update_by', models.CharField(default='admin', max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete')),
                ('location', models.CharField(max_length=100)),
                ('documentID', models.CharField(max_length=100, unique=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'in plan'), (2, 'in processing'), (3, 'Approved')], default=1, verbose_name='status')),
                ('version', models.IntegerField(default=0)),
                ('note', models.TextField(help_text='note', verbose_name='note')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Document',
                'ordering': ('documentID',),
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(default='admin', max_length=100)),
                ('update_by', models.CharField(default='admin', max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete')),
                ('folder_name', models.CharField(max_length=100)),
                ('p_id', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('right', models.SmallIntegerField(choices=[(1, 'read'), (2, 'read + update'), (3, 'read + update + create'), (4, 'read + update + create + delete')], default=1, verbose_name='right')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(default='admin', max_length=100)),
                ('update_by', models.CharField(default='admin', max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete')),
                ('node_name', models.CharField(max_length=100)),
                ('p_id', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(default='admin', max_length=100)),
                ('update_by', models.CharField(default='admin', max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete')),
                ('role_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role_Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(default='admin', max_length=100)),
                ('update_by', models.CharField(default='admin', max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.node')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role_Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(default='admin', max_length=100)),
                ('update_by', models.CharField(default='admin', max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.folder')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.role')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_by', models.CharField(default='admin', max_length=100)),
                ('update_by', models.CharField(default='admin', max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='update time')),
                ('is_delete', models.BooleanField(default=False, verbose_name='delete')),
                ('file_name', models.CharField(max_length=100)),
                ('size', models.CharField(max_length=100)),
                ('version', models.IntegerField(default=0)),
                ('type', models.SmallIntegerField(choices=[(1, 'doc'), (2, 'excel'), (3, 'pdf'), (4, 'image'), (5, 'dwg')], default=1, verbose_name='type')),
                ('note', models.TextField(help_text='note', verbose_name='note')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.document')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.folder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('company', models.SmallIntegerField(choices=[(1, '01_company'), (2, '02_company')], default=1, verbose_name='Company')),
                ('pos', models.SmallIntegerField(choices=[(1, '01_intern'), (2, '02_extern')], default=1, verbose_name='Position')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dms.role')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
